2025-05-12 15:55:35,161 INFO    MainThread:4117345 [wandb_setup.py:_flush():67] Current SDK version is 0.19.9
2025-05-12 15:55:35,161 INFO    MainThread:4117345 [wandb_setup.py:_flush():67] Configure stats pid to 4117345
2025-05-12 15:55:35,161 INFO    MainThread:4117345 [wandb_setup.py:_flush():67] Loading settings from /t9k/mnt/.config/wandb/settings
2025-05-12 15:55:35,162 INFO    MainThread:4117345 [wandb_setup.py:_flush():67] Loading settings from /t9k/mnt/code/CLM-access/scripts/wandb/settings
2025-05-12 15:55:35,162 INFO    MainThread:4117345 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-05-12 15:55:35,162 INFO    MainThread:4117345 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /t9k/mnt/code/CLM-access/save/test/logs/wandb/run-20250512_155535-k2zurk9r/logs/debug.log
2025-05-12 15:55:35,162 INFO    MainThread:4117345 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /t9k/mnt/code/CLM-access/save/test/logs/wandb/run-20250512_155535-k2zurk9r/logs/debug-internal.log
2025-05-12 15:55:35,162 INFO    MainThread:4117345 [wandb_init.py:init():781] calling init triggers
2025-05-12 15:55:35,162 INFO    MainThread:4117345 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-12 15:55:35,162 INFO    MainThread:4117345 [wandb_init.py:init():809] starting backend
2025-05-12 15:55:35,162 INFO    MainThread:4117345 [wandb_init.py:init():813] sending inform_init request
2025-05-12 15:55:35,167 INFO    MainThread:4117345 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-12 15:55:35,167 INFO    MainThread:4117345 [wandb_init.py:init():823] backend started and connected
2025-05-12 15:55:35,170 INFO    MainThread:4117345 [wandb_init.py:init():915] updated telemetry
2025-05-12 15:55:35,172 INFO    MainThread:4117345 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-05-12 15:55:36,899 INFO    MainThread:4117345 [wandb_init.py:init():1014] starting run threads in backend
2025-05-12 15:55:37,118 INFO    MainThread:4117345 [wandb_run.py:_console_start():2454] atexit reg
2025-05-12 15:55:37,118 INFO    MainThread:4117345 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-05-12 15:55:37,118 INFO    MainThread:4117345 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-05-12 15:55:37,118 INFO    MainThread:4117345 [wandb_run.py:_redirect():2394] Redirects installed.
2025-05-12 15:55:37,121 INFO    MainThread:4117345 [wandb_init.py:init():1056] run started, returning control to user process
2025-05-12 15:55:37,159 INFO    MainThread:4117345 [wandb_run.py:_config_callback():1327] config_cb None None {'config': {'project_name': 'CLM-access', 'seed': 1, 'atac_vocab_size': 2002, 'encoder_layers': 8, 'encoder_embed_dim': 256, 'encoder_attention_heads': 8, 'encoder_ffn_embed_dim': 256, 'activation_fn': 'gelu', 'activation_dropout': 0.0, 'pre_norm': False, 'multiway': True, 'optim_type': 'adamw', 'learning_rate': 0.0001, 'attention_dropout': 0.1, 'dropout': 0.1, 'resume_from': None, 'fast_dev_run': False, 'val_check_interval': None, 'test_only': False, 'use_sharded_training': False, 'resume_during_training': False, 'checkpoint_activations': False, 'every_n_train_steps': 200, 'load_to_cpu': False, 'per_gpu_batchsize': 8, 'num_gpus': 1, 'batch_size': 16, 'grad_steps': 1, 'num_nodes': 1, 'load_path': '', 'num_workers': 8, 'precision': 16, 'pin_mem': True, 'max_epoch': 300, 'max_steps': 4000000, 'num_warmup_steps': 50, 'adam_weight_decay': 0.01, 'end_lr': 0, 'atac_dataset_path': '/t9k/mnt/scllm/liuziqiang/EpiAgent_data/batch/dataset_34_37_numpy_train', 'atac_vocab_file': '/t9k/mnt/scllm/scCLIP/atac/patched_2000_unified/scCLIP_ATAC_vocabulary_with_special_2000_unified.json', 'batch_correction': True, 'cell_type_annotation': False, 'context_length': 2000, 'dirpath': '/t9k/mnt/code/CLM-access/save/test/', 'embedding_type': 'cls', 'exp_name': 'ATAC-finetune', 'input_mod': 'ATAC', 'log_dir': '/t9k/mnt/code/CLM-access/save/test/logs', 'mask_id': 1998, 'mask_token': False, 'model_load_path': None, 'model_task': 'finetune', 'pad_id': 1999, 'peak_length': 600, 'resume_from_checkpoint': None, 'task': 'atacmlm', 'batch_number': 4, 'dist_eval': {}, 'gene_tokens': '[2000  628 1597 ...  204 1246 1999]'}}
2025-05-12 15:56:28,135 INFO    MsgRouterThr:4117345 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-05-12 15:56:31,509 ERROR   MainThread:4117345 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-12 15:56:31,510 ERROR   MainThread:4117345 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/t9k/mnt/.conda/envs/cellstory-v1/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
